name: Android Debug APK (Clean Build)

on:
  workflow_dispatch: # lo lanzas a mano desde Actions

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Cache de Gradle y validación de wrapper
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 1) Limpieza total
      - name: Clean
        run: ./gradlew clean --no-daemon

      # 2) Compilar debug SIN caché de build, con stacktrace para depurar
      - name: Assemble Debug
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace --no-build-cache

      # 3) (Sanity) Comprobar que xposed_init está empaquetado en el APK
      - name: Check xposed_init packed
        run: unzip -l app/build/outputs/apk/debug/*-debug*.apk | grep -q "assets/xposed_init"

      # 4) (Sanity) Verificar meta-data Xposed/LSPosed en el merged manifest
      - name: Locate merged manifest
        id: find_manifest
        run: |
          MF=$(grep -Rl --include="AndroidManifest.xml" "merged" app/build/intermediates | head -n 1 || true)
          test -n "$MF"
          echo "manifest=$MF" >> $GITHUB_OUTPUT

      - name: Check meta-data in merged manifest
        run: |
          MF="${{ steps.find_manifest.outputs.manifest }}"
          grep -q 'android:name="xposedmodule"' "$MF"
          # Requiere xposedminversion O bien xposedsharedprefs (si usas el modo nuevo)
          if ! grep -q 'android:name="xposedminversion"' "$MF" && ! grep -q 'android:name="xposedsharedprefs"' "$MF"; then
            echo "Missing xposedminversion or xposedsharedprefs in merged manifest"
            exit 1
          fi

      # 5) Guard: evitar empaquetar Xposed API por error (debe ser compileOnly, nunca implementation)
      - name: Check compileOnly for Xposed API
        run: |
          ! grep -R "implementation.*de\.robv\.android\.xposed:api" app/build.gradle

      # 6) Subir APK y merged manifest como artefactos
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*-debug*.apk
          retention-days: 7

      - name: Upload merged manifest
        uses: actions/upload-artifact@v4
        with:
          name: merged-manifest
          path: ${{ steps.find_manifest.outputs.manifest }}
          retention-days: 7
